---
title: "Class 03 - R Basics"
author: "Dominic Sanchez"
date: "2026-08-31"
output: 
  html_document:
    toc: true # toc - table of contents
    toc_float: true # toc will float along the left side of the screen as you scroll instead of just being at the top
    number_sections: true # numbers off the sections
    code_folding: show # allows you to hide and show code segments in markdown
    code_download: true
---
# include = false takes out the code from the markdown but keeps the output
# echo = FALSE, wouldn't see the chunk

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Cincy Crash Data

```{r cincy_crashes}
crashes_per_day = 30125 / 365
crashes_per_day


crashes_by_day = c(2020, 2241, 2327, 2285,
                   2380, 1866, 1664)
names(crashes_by_day) = c("Mon", "Tue", "Wed", "Thu",
                          "Fri", "Sat", "Sun")

crashes_by_day > 2000        # seven answers -- returns a table of booleans per variable (day)
crashes_by_day

sum(crashes_by_day > 2000)   # days above 2,000
```


## Type of `crashes_by_day`

```{r typeof_vec}
typeof(crashes_by_day)

crashes_by_day_int = c(2020L, 2241L, 2327L, 2285L,
                   2380L, 1866L, 1664L)
names(crashes_by_day_int) = c("Mon", "Tue", "Wed", "Thu",
                          "Fri", "Sat", "Sun")

typeof(crashes_by_day_int)
```



