---
title: "Class 05"
author: "Dominic Sanchez"
date: "2026-09-09"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    code_download: true
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Game 01: Subsetting Lists

```{r game01}
campus = jsonlite::fromJSON(
  "https://isa401-find-your-seat.vercel.app/campus.json")

names(campus) # shows the named elements within a list (or vector) or the cols in a data frame

fsb = campus$Farmer
# campus[['Farmer']] by name or campus[[5]] by position

fsb$code
```


```{r game01L2}
floors <- fsb$floors
names(floors)

sec_floor <- floors$`2`
names(sec_floor)

sec_floor$sections
```

```{r}
names(fsb[[8]]) # FSB floors
fsb[[8]][[3]] # or fsb[[8]]$`2`
```


```{r game01L3}
names(sec_floor$rooms)

sec_floor_rooms <- sec_floor[['rooms']]
View(sec_floor_rooms)
sec_floor_rooms[6, 2] # sec_floor_rooms[6, 'isa_sections']

```



## Read Excel Data

```{r occupation}
occupation <- readxl::read_excel(
  path = "../data/occupation.xlsx",
  sheet = 5, # sheet = Table 1.4
  skip = 1
)

# - when you subset in R drops these specific things (rows or columns)
# given that theythey are three, put them in a vector
# notice the "," after the parantheses
# nothing after the comma which means all columns
# instead of that space --> 1:7
occupation = occupation[-c(32, 33, 34), ]
# alternatively occupation = occupation[1:31, ]

dplyr::glimpse(occupation) # gives quick glimpse of columns and data
```


## Read JSON Data

```{r webJSON}
json_url = paste0(
  "https://data.cincinnati-oh.gov/",
  "resource/rvmt-pkmq.json?$limit=100")
# or: json_url = "https://data.cincinnati-oh.gov/"resource/rvmt-pkmq.json?$limit=100"

crashes_json = jsonlite::fromJSON(json_url)
dplyr::glimpse(
  crashes_json[, c("crashdate", "dayofweek",
                   "crashseverity", "age")])
```


## Game 2

```{r cybersec_game}
logins = readr::read_csv("https://isa401-import-heist.vercel.app/api/stage1?seat=L2-2&s=B")

logins


log = jsonlite::fromJSON("https://isa401-import-heist.vercel.app/api/stage2?key=smithj31&seat=L2-2&s=B")
log$events

jsonlite::fromJSON("https://isa401-import-heist.vercel.app/api/finish?code=6&seat=L2-2&s=B")

```








